/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConfiguradorRouteImport } from './routes/configurador'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutRecusadoRouteImport } from './routes/checkout.recusado'
import { Route as CheckoutPixRouteImport } from './routes/checkout.pix'
import { Route as CheckoutPendenteRouteImport } from './routes/checkout.pendente'
import { Route as CheckoutFalhaRouteImport } from './routes/checkout.falha'
import { Route as CheckoutAprovadoRouteImport } from './routes/checkout.aprovado'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguradorRoute = ConfiguradorRouteImport.update({
  id: '/configurador',
  path: '/configurador',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutRecusadoRoute = CheckoutRecusadoRouteImport.update({
  id: '/recusado',
  path: '/recusado',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPixRoute = CheckoutPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPendenteRoute = CheckoutPendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFalhaRoute = CheckoutFalhaRouteImport.update({
  id: '/falha',
  path: '/falha',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutAprovadoRoute = CheckoutAprovadoRouteImport.update({
  id: '/aprovado',
  path: '/aprovado',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configurador': typeof ConfiguradorRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/checkout/aprovado': typeof CheckoutAprovadoRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/recusado': typeof CheckoutRecusadoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configurador': typeof ConfiguradorRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/checkout/aprovado': typeof CheckoutAprovadoRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/recusado': typeof CheckoutRecusadoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configurador': typeof ConfiguradorRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/checkout/aprovado': typeof CheckoutAprovadoRoute
  '/checkout/falha': typeof CheckoutFalhaRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/pix': typeof CheckoutPixRoute
  '/checkout/recusado': typeof CheckoutRecusadoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/configurador'
    | '/conta'
    | '/login'
    | '/produtos'
    | '/checkout/aprovado'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/pix'
    | '/checkout/recusado'
    | '/checkout/sucesso'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/configurador'
    | '/conta'
    | '/login'
    | '/produtos'
    | '/checkout/aprovado'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/pix'
    | '/checkout/recusado'
    | '/checkout/sucesso'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/configurador'
    | '/conta'
    | '/login'
    | '/produtos'
    | '/checkout/aprovado'
    | '/checkout/falha'
    | '/checkout/pendente'
    | '/checkout/pix'
    | '/checkout/recusado'
    | '/checkout/sucesso'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ConfiguradorRoute: typeof ConfiguradorRoute
  ContaRoute: typeof ContaRoute
  LoginRoute: typeof LoginRoute
  ProdutosRoute: typeof ProdutosRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurador': {
      id: '/configurador'
      path: '/configurador'
      fullPath: '/configurador'
      preLoaderRoute: typeof ConfiguradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/recusado': {
      id: '/checkout/recusado'
      path: '/recusado'
      fullPath: '/checkout/recusado'
      preLoaderRoute: typeof CheckoutRecusadoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pix': {
      id: '/checkout/pix'
      path: '/pix'
      fullPath: '/checkout/pix'
      preLoaderRoute: typeof CheckoutPixRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pendente': {
      id: '/checkout/pendente'
      path: '/pendente'
      fullPath: '/checkout/pendente'
      preLoaderRoute: typeof CheckoutPendenteRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/falha': {
      id: '/checkout/falha'
      path: '/falha'
      fullPath: '/checkout/falha'
      preLoaderRoute: typeof CheckoutFalhaRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/aprovado': {
      id: '/checkout/aprovado'
      path: '/aprovado'
      fullPath: '/checkout/aprovado'
      preLoaderRoute: typeof CheckoutAprovadoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutAprovadoRoute: typeof CheckoutAprovadoRoute
  CheckoutFalhaRoute: typeof CheckoutFalhaRoute
  CheckoutPendenteRoute: typeof CheckoutPendenteRoute
  CheckoutPixRoute: typeof CheckoutPixRoute
  CheckoutRecusadoRoute: typeof CheckoutRecusadoRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutAprovadoRoute: CheckoutAprovadoRoute,
  CheckoutFalhaRoute: CheckoutFalhaRoute,
  CheckoutPendenteRoute: CheckoutPendenteRoute,
  CheckoutPixRoute: CheckoutPixRoute,
  CheckoutRecusadoRoute: CheckoutRecusadoRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ConfiguradorRoute: ConfiguradorRoute,
  ContaRoute: ContaRoute,
  LoginRoute: LoginRoute,
  ProdutosRoute: ProdutosRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
